name: HawkScan Integration Tests
on:
  repository_dispatch:
    types: [integration-test]
jobs:
  hawkscan:
    name: HawkScan Action Integration Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Create app directory for ${{ github.event.client_payload.repoName }}
        run: mkdir -p __tests__/integration-tests/apps
      - name: Navigate to app directory to clone ${{ github.event.client_payload.repoName }}
        run: cd __tests__/integration-tests/apps/
      - name: Checkout ${{ github.event.client_payload.repoName }} repository
        run: git clone https://github.com/${{ github.event.client_payload.repoOrg }}/${{ github.event.client_payload.repoName }}.git
      - name: Navigate to app directory to clone ${{ github.event.client_payload.repoName }}
        run: cd ${{ github.event.client_payload.repoName }}
      - name: Debugging 1
        run: pwd
      - name: Debugging 1
        run: ls -lah
      - name: Run ${{ github.event.client_payload.repoName }}
        run: docker-compose up -d
      - name: Navigate to scan config directory
        run: cd ${{ env.GITHUB_WORKSPACE }}/__tests__/integration-tests/configs/${{ github.event.client_payload.repoName }}
      - name: Run HawkScan
        id: run-hawkscan
        uses: stackhawk/hawkscan-action@main
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          configurationFiles: ${{ github.event.client_payload.configFile }}
          sourceURL: ${{ github.event.client_payload.hawkscanSourceUrl }}
          version: ${{ github.event.client_payload.hawkscanVersion }}
          verbose: ${{ github.event.client_payload.verbose }}
        env:
          APPLICATION_ID: ${{ github.event.client_payload.appId }}