name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test
      env:


  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        api-key: ${{ secrets.SHAWK_API_KEY }}
        environment-variables: HOST APP_ENV APP_ID
        configuration-files: stackhawk.yml stackhawk-test.yml
        network: bridge
        image: zconger/hawkscan
        version: beta

      env:
        ACTIONS_RUNNER_DEBUG: true
        ACTIONS_STEP_DEBUG: true
        HOST: localhost:5000
        APP_ENV: ApPeNvIrOnMeNt
