name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:

  # unit tests
  units:
    env:
      SHAWK_API_KEY: ${{ secrets.SHAWK_API_KEY }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm clean-install
    - run: env
    - run: npm test

  # test action works running from the graph
  max-config:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        api-key: ${{ secrets.SHAWK_API_KEY }}
        dry-run: true
        environment-variables: HOST APP_ENV APP_ID
        configuration-files: stackhawk.yml stackhawk-test.yml
        network: bridge
        image: zconger/hawkscan
        version: beta
      env:
        SHAWK_API_KEY: ${{ secrets.SHAWK_API_KEY }}
        ACTIONS_RUNNER_DEBUG: true
        ACTIONS_STEP_DEBUG: true
        HOST: localhost:5000
        APP_ENV: ApPeNvIrOnMeNt

  min-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          api-key: ${{ secrets.SHAWK_API_KEY }}
          dry-run: true
        env:
          SHAWK_API_KEY: ${{ secrets.SHAWK_API_KEY }}
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
          HOST: localhost:5000

  acid-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          api-key: ${{ secrets.SHAWK_API_KEY }}
          environment-variables: SHAWK_RESULTS_ENDPOINT SHAWK_AUTH_ENDPOINT
          configuration-files: test/stackhawk.yml
        env:
          SHAWK_API_KEY: ${{ secrets.SHAWK_API_KEY }}
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true